In [2]:
import numpy as np

###  Basics

In [3]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9,0,8,0,7,0],[6,0,5,0,4,0]])
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [6]:
# Get dimension
a.ndim

1

In [7]:
# Get Shape
b.shape

(2, 6)

In [8]:
# Get Type
b.dtype

dtype('int32')

In [9]:
# Get Size
b.itemsize

4

In [10]:
# get total size
a.nbytes

6

### Accessing / Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r,c]
a[1,5]

13

In [13]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy  [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20

a[0, 1:-1:2]

array([2, 4, 6])

### 3-D Example

In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific  element (work outside in)
b[0,1,1]

4

In [19]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [20]:
# Replace
b[:,1,:] = [[9,9],[8,8]]

In [21]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing different types of Arrays

In [22]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# All 1s in matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [25]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [26]:
# Any other (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.25544258, 0.5277326 ],
       [0.47701035, 0.8802909 ],
       [0.09277645, 0.86002822],
       [0.8465745 , 0.75564014]])

In [29]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[3, 1, 5],
       [2, 0, 3],
       [1, 5, 3]])

In [30]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0 )
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!

In [33]:
a = np.array([1,2,3])
b = a.copy() # just to copy the content only
b[0] = 100
print(a)

[1 2 3]


### Mathematics

In [34]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [35]:
a + 2

array([3, 4, 5, 6])

In [36]:
a - 2

array([-1,  0,  1,  2])

In [37]:
a * 2

array([2, 4, 6, 8])

In [38]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [40]:
a ** 2

array([ 1,  4,  9, 16])

In [41]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [65]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

### Linear Algebra

In [67]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

##### Two matrices are able to multiply if "Columns of first matrix is equal to the rows of the second matix"

In [72]:
# Find the Determinent
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
## Reference docs (https://docs.scipy.org/numpy/reference/routines.linalg.html)

### Statistics

In [73]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.min(stats)

1

In [77]:
np.max(stats, axis=1) # row wise

array([3, 6])

In [78]:
np.sum(stats)

21

### Reorganizing Arrays

In [81]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [82]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Miscellaneous
#### Load Data from File

In [88]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

array([[2., 3., 4., 5., 6.],
       [5., 6., 7., 8., 9.]])

### Boolean Masking and Advanced Indexing

In [90]:
filedata >= 5

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [91]:
filedata[filedata > 5]

array([6., 6., 7., 8., 9.])

In [92]:
## You can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])

In [95]:
np.any(filedata > 5, axis=0)

array([False,  True,  True,  True,  True])

In [96]:
((filedata > 5) & (filedata < 7))

array([[False, False, False, False,  True],
       [False,  True, False, False, False]])

In [97]:
~((filedata > 5) & (filedata < 7))

array([[ True,  True,  True,  True, False],
       [ True, False,  True,  True,  True]])