In [1]:
import torch

In [3]:
x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])

In [6]:
print(x.shape)  # One entity of two items
print(y.shape) # Two entities of one item each
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [9]:
x = torch.tensor([False, 1, 2.0])
print(x)

tensor([0., 1., 2.])


In [10]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
torch.randint(low=0, high=10, size=(3, 4))

tensor([[8, 5, 4, 6],
        [7, 2, 4, 3],
        [1, 1, 7, 0]])

In [13]:
torch.rand(3, 4)

tensor([[0.0203, 0.1864, 0.0179, 0.6008],
        [0.6754, 0.3792, 0.5890, 0.4087],
        [0.6588, 0.5708, 0.5020, 0.0894]])

In [15]:
import numpy as np
x = np.array([[10, 20, 30], [2, 3, 4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [22]:
help(torch.Tensor.add)

Help on method_descriptor:

add(...)
    add(other, *, alpha=1) -> Tensor
    
    Add a scalar or tensor to :attr:`self` tensor. If both :attr:`alpha`
    and :attr:`other` are specified, each element of :attr:`other` is scaled by
    :attr:`alpha` before being used.
    
    When :attr:`other` is a tensor, the shape of :attr:`other` must be
    :ref:`broadcastable <broadcasting-semantics>` with the shape of the underlying
    tensor
    
    See :func:`torch.add`

